# Generated by Django 3.2.20 on 2024-01-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdeleted',
            name='origin_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
