# Generated by Django 3.2.20 on 2023-07-07 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
        migrations.CreateModel(
            name='DayMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.day')),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.meal')),
            ],
        ),
    ]
