# Generated by Django 3.2.20 on 2024-01-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payinfo',
            name='order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
