# Generated by Django 3.2.20 on 2023-07-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20230707_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymeal',
            name='for_student',
            field=models.BooleanField(default=True),
        ),
    ]
