# Generated by Django 3.2.20 on 2024-01-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_commentdeleted_origin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menucomment',
            old_name='_id',
            new_name='comment_id',
        ),
    ]
