# Generated by Django 3.2.20 on 2023-07-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_daymeal_for_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymeal',
            name='for_student',
            field=models.BooleanField(),
        ),
    ]
