# Generated by Django 3.2.20 on 2024-01-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_day_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daymeal',
            name='for_student',
        ),
        migrations.RemoveField(
            model_name='daymeal',
            name='is_additional',
        ),
        migrations.AddField(
            model_name='daymeal',
            name='menu_type',
            field=models.CharField(default='N', max_length=1),
            preserve_default=False,
        ),
    ]
