# Generated by Django 3.2.20 on 2023-09-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_daymeal_for_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymeal',
            name='is_additional',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
