# Generated by Django 3.2.20 on 2024-01-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20240113_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymeal',
            name='menu_type',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
