# Generated by Django 3.2.20 on 2024-01-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20240116_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdeleted',
            name='menu_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='daymeal',
            name='menu_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='menucomment',
            name='menu_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='menulike',
            name='menu_id',
            field=models.CharField(max_length=40),
        ),
    ]
