# Generated by Django 3.2.20 on 2024-01-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20240116_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayMealDeleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(default='N', max_length=1)),
                ('menu_id', models.CharField(max_length=40)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.day')),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.meal')),
            ],
            options={
                'db_table': 'day_meal_deleted',
            },
        ),
    ]
